FORMAT: 1A
HOST: https://descartes-api.quantumstack.xyz/

# Descartes

I think, therefore I am.

[Open-source](https://github.com/quantumstack/descartes), educational web application.

## Authentication Collection [/auth]

This API uses OAuth v2 Bearer Token / Personal Access Token for its authentication.

### Signup [POST /auth/signup]

Create a new user.

+ Request (application/json)
    + Body

            {
                "email": "aditya@example.com",
                "password": "example_password",
                "fullName": "Aditya Pillai"
            }

+ Response 200 (application/json)

        {
            "success": true,
            "message": "You have successfully created an account."
        }
    
        
+ Request (application/json)
    + Body

            {
                "email": "aditya@example.com",
                "password": "example_password",
                "fullName": "Aditya Pillai"
            }
        
+ Response 409 (application/json)

        {
            "success": false,
            "error": "user-already-exists",
            "message": "A user with this email address already exists."
        }


+ Request (application/json)
    + Body

            {
                "email": "aditya@example.com",
                "password": "short",
                "fullName": "Aditya Pillai"
            }
            
+ Response 400 (application/json)

        {
            "success": false,
            "error": "password-too-short",
            "message": "Please provide a password of length 8+."
        }
        
+ Request (application/json)
    + Body

            {
                "password": "example_password",
                "fullName": "Aditya Pillai"
            }
        
+ Response 400 (application/json)

        {
            "success": false,
            "error": "no-email",
            "message": "Please provide your email."
        }

+ Request (application/json)
    + Body

            {
                "email": "aditya@example.com",
                "fullName": "Aditya Pillai"
            }
            
+ Response 400 (application/json)

        {
            "success": false,
            "error": "no-password",
            "message": "Please provide a password"
        }

+ Request (application/json)
    + Body

            {
                "email": "aditya@example.com",
                "password": "example_password",
            }
            

+ Response 400 (application/json)

        {
            "success": false,
            "error": "no-fullname",
            "message": "Please provide your full name."
        }


### Login [POST /auth/login]

Login to an existing user account.

+ Request (application/json)
    + Body

            {
                "email": "aditya@example.com",
                "password": "example_password"
            }
            
+ Response 200 (application/json)

        {
            "success": true,
            "message": "You have successfully logged in.",
            "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjI0LCJpYXQiOjE1NTg2MzI2NTN9.gpRK6QPQpPkHJ7iOjFuL7mvaghJFdQJNnCRuDimlaKM",
            "user": {
                "userId": 24,
                "email": "aditya@example.com",
                "fullName": "Aditya Pillai"
            }
        }