import { createActions } from 'redux-actions';

export const LOG_IN_INPUT_BLUR = 'LOG_IN_INPUT_BLUR';
export const SIGN_UP_CAPTCHA = 'SIGN_UP_CAPTCHA';
export const PAYMENTS_DEHYDRATE = 'PAYMENTS_DEHYDRATE';
export const PAYMENTS_RECEIVE = 'PAYMENTS_RECEIVE';
export const INSTRUCTOR_COURSES_DEHYDRATE = 'INSTRUCTOR_COURSES_DEHYDRATE';
export const INSTRUCTOR_COURSES_RECEIVE = 'INSTRUCTOR_COURSES_RECEIVE';
export const INSTRUCTOR_COURSE_DEHYDRATE = 'INSTRUCTOR_CUORSE_DEHYDRATE';
export const STUDENT_COURSES_DEHYDRATE = 'STUDENT_COURSES_DEHYDRATE';
export const STUDENT_COURSES_RECEIVE = 'STUDENT_COURSES_RECEIVE';
export const STUDENT_COURSE_DEHYDRATE = 'STUDENT_COURSE_DEHYDRATE';
export const STUDENT_COURSE_UNFAKE_SCORE = 'STUDENT_COURSE_UNFAKE_SCORE';
export const STUDENT_COURSE_UNFAKE_ASSIGNMENT = 'STUDENT_COURSE_UNFAKE_ASSIGNMENT';
export const STUDENT_COURSE_SCORE_RESET = 'STUDENT_COURSE_SCORE_RESET';

export const {
  logInInputBlur,
  signUpCaptcha,
  paymentsDehydrate,
  paymentsReceive,
  instructorCoursesDehydrate,
  instructorCoursesReceive,
  instructorCourseDehydrate,
  studentCoursesDehydrate,
  studentCoursesReceive,
  studentCourseDehydrate,
  studentCourseUnfakeScore,
  studentCourseScoreReset,
} = createActions(
  LOG_IN_INPUT_BLUR,
  SIGN_UP_CAPTCHA,
  PAYMENTS_DEHYDRATE,
  PAYMENTS_RECEIVE,
  INSTRUCTOR_COURSES_DEHYDRATE,
  INSTRUCTOR_COURSES_RECEIVE,
  INSTRUCTOR_COURSE_DEHYDRATE,
  STUDENT_COURSES_DEHYDRATE,
  STUDENT_COURSES_RECEIVE,
  STUDENT_COURSE_DEHYDRATE,
  STUDENT_COURSE_UNFAKE_SCORE,
  STUDENT_COURSE_SCORE_RESET,
);
